const cursos = [ { nombre: "💋 Anatomía I", codigo: "MED101", semestre: 1, prerequisitos: [] }, { nombre: "🤜 Genética", codigo: "MED102", semestre: 1, prerequisitos: [] }, { nombre: "🔬 Histología I", codigo: "MED103", semestre: 1, prerequisitos: [] }, { nombre: "💻 Informática Aplicada", codigo: "MED104", semestre: 1, prerequisitos: [] },

{ nombre: "🦠 Anatomía II", codigo: "MED201", semestre: 2, prerequisitos: ["MED101"] }, { nombre: "🧹 Embriología", codigo: "MED202", semestre: 2, prerequisitos: ["MED102"] }, { nombre: "🧪 Histología II", codigo: "MED203", semestre: 2, prerequisitos: ["MED103"] }, { nombre: "🧪 Bioquímica I", codigo: "MED204", semestre: 2, prerequisitos: [] }, { nombre: "🏥 Salud Pública I", codigo: "MED205", semestre: 2, prerequisitos: [] }, { nombre: "📘 Inglés Técnico I", codigo: "MED206", semestre: 2, prerequisitos: [] },

{ nombre: "🧪 Bioquímica II", codigo: "MED301", semestre: 3, prerequisitos: ["MED204"] }, { nombre: "🦡 Fisiología I", codigo: "MED302", semestre: 3, prerequisitos: ["MED201"] }, { nombre: "🪗 Microbiología I", codigo: "MED303", semestre: 3, prerequisitos: [] }, { nombre: "📉 Patología I", codigo: "MED304", semestre: 3, prerequisitos: ["MED201", "MED203"] }, { nombre: "🔭 Biofísica", codigo: "MED305", semestre: 3, prerequisitos: ["MED201"] }, { nombre: "📗 Inglés Técnico II", codigo: "MED306", semestre: 3, prerequisitos: ["MED206"] },

{ nombre: "🧪 Bioquímica III", codigo: "MED401", semestre: 4, prerequisitos: ["MED301"] }, { nombre: "🦡 Fisiología II", codigo: "MED402", semestre: 4, prerequisitos: ["MED302"] }, { nombre: "🪗 Microbiología II", codigo: "MED403", semestre: 4, prerequisitos: ["MED303"] }, { nombre: "🦠 Parasitología", codigo: "MED404", semestre: 4, prerequisitos: ["MED303"] }, { nombre: "📉 Patología II", codigo: "MED405", semestre: 4, prerequisitos: ["MED304"] }, { nombre: "🧠 Psicología Médica", codigo: "MED406", semestre: 4, prerequisitos: [] }, { nombre: "👥 Sociología y Ética Médica", codigo: "MED407", semestre: 4, prerequisitos: [] }, { nombre: "🥗 Electiva (Nutrición)", codigo: "MED408", semestre: 4, prerequisitos: [] },

{ nombre: "🧪 Semiología General y Especial I", codigo: "MED501", semestre: 5, prerequisitos: ["MED402", "MED401"] }, { nombre: "🔪 Técnica Quirúrgica I", codigo: "MED502", semestre: 5, prerequisitos: ["MED402"] }, { nombre: "💊 Farmacología y Terapéutica I", codigo: "MED503", semestre: 5, prerequisitos: ["MED402", "MED401"] }, { nombre: "🧸 Fisiopatología I", codigo: "MED504", semestre: 5, prerequisitos: ["MED402", "MED405"] }, { nombre: "📉 Patología III", codigo: "MED505", semestre: 5, prerequisitos: ["MED405"] }, { nombre: "🫡 Inmunología", codigo: "MED506", semestre: 5, prerequisitos: ["MED403", "MED405"] },

{ nombre: "🧪 Semiología General y Especial II", codigo: "MED601", semestre: 6, prerequisitos: ["MED501"] }, { nombre: "🔪 Técnica Quirúrgica II", codigo: "MED602", semestre: 6, prerequisitos: ["MED502"] }, { nombre: "💊 Farmacología y Terapéutica II", codigo: "MED603", semestre: 6, prerequisitos: ["MED503"] }, { nombre: "🧸 Fisiopatología II", codigo: "MED604", semestre: 6, prerequisitos: ["MED504"] }, { nombre: "💉 Anestesiología", codigo: "MED605", semestre: 6, prerequisitos: ["MED402"] }, { nombre: "🏥 Salud Pública II", codigo: "MED606", semestre: 6, prerequisitos: ["MED205"] }, { nombre: "🖼️ Imagenología", codigo: "MED607", semestre: 6, prerequisitos: ["MED201"] } ];

